In [1]:
import pandas as pd , numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix , accuracy_score
from sklearn.preprocessing import StandardScaler

In [2]:
dia = pd.read_csv('Diabetes.csv')
print(dia.head(),"\n----")
dia.info()
print("----")
print(dia.shape)
print("----")
print(dia.isnull().sum(),"\n----")
dia.duplicated().sum()


   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetespedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1   
----
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                

np.int64(0)

In [3]:
heart = pd.read_csv('Heart Disease.csv')
print(heart.head(),"\n----")
heart.info()
print("----")
print(heart.shape)
print("----")
print(heart.isnull().sum(),"\n----")
heart.duplicated().sum()


   Unnamed: 0  age  sex  chest pain type  resting bps  cholesterol  \
0           0   40    1                2          140        289.0   
1           1   49    0                3          160        180.0   
2           2   37    1                2          130        283.0   
3           3   48    0                4          138        214.0   
4           4   54    1                3          150        195.0   

   fasting blood sugar  resting ecg  max heart rate  exercise angina  oldpeak  \
0                    0            0             172                0      0.0   
1                    0            0             156                0      1.0   
2                    0            1              98                0      0.0   
3                    0            0             108                1      1.5   
4                    0            0             122                0      0.0   

   ST slope  target  
0         1       0  
1         2       1  
2         1       0  
3   

np.int64(0)

In [4]:
neu = pd.read_csv('neurological disorder.csv')
print(neu.head(),"\n----")
neu.info()
print("----")
print(neu.shape)
print("----")
print(neu.isnull().sum(),"\n----")
neu.duplicated().sum()


             name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0  phon_R01_S01_1      119.992       157.302        74.997         0.00784   
1  phon_R01_S01_2      122.400       148.650       113.819         0.00968   
2  phon_R01_S01_3      116.682       131.111       111.555         0.01050   
3  phon_R01_S01_4      116.676       137.871       111.366         0.00997   
4  phon_R01_S01_5      116.014       141.781       110.655         0.01284   

   MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0           0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1           0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2           0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3           0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4           0.00011   0.00655   0.00908     0.01966       0.06425  ...   

   Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0      0.0654

np.int64(0)

In [5]:
heart.drop("Unnamed: 0", axis=1, inplace=True)
neu.drop("name", axis=1, inplace=True)

In [6]:
print("Diabetes target   :", dia['Outcome'].value_counts(),"\n")
print("Heart target      :", heart['target'].value_counts(),"\n")
print("Neuro target      :", neu['status'].value_counts(),"\n")

Diabetes target   : Outcome
0    500
1    268
Name: count, dtype: int64 

Heart target      : target
0    528
1    520
Name: count, dtype: int64 

Neuro target      : status
1    541
0    459
Name: count, dtype: int64 



In [7]:
x_dia = dia.drop("Outcome", axis=1)
y_dia = dia["Outcome"]

x_heart = heart.drop("target", axis=1)
y_heart = heart["target"]

x_neu = neu.drop("status", axis=1)
y_neu = neu["status"]

In [8]:
x_train_dia, x_test_dia, y_train_dia, y_test_dia = train_test_split(
    x_dia, y_dia, test_size=0.2, random_state=42
)

In [9]:
x_train_heart, x_test_heart, y_train_heart, y_test_heart = train_test_split(
    x_heart, y_heart, test_size=0.2, random_state=42
)

In [10]:
x_train_neu, x_test_neu, y_train_neu, y_test_neu = train_test_split(
    x_neu, y_neu, test_size=0.2, random_state=42
)

In [11]:
print("Diabetes   → Train:", x_train_dia.shape,   "Test:", x_test_dia.shape)
print("Heart      → Train:", x_train_heart.shape, "Test:", x_test_heart.shape)
print("Neuro      → Train:", x_train_neu.shape,   "Test:", x_test_neu.shape)

Diabetes   → Train: (614, 8) Test: (154, 8)
Heart      → Train: (838, 11) Test: (210, 11)
Neuro      → Train: (800, 22) Test: (200, 22)


In [12]:
dia_model = RandomForestClassifier(random_state=42)
dia_model.fit(x_train_dia, y_train_dia)


RandomForestClassifier(random_state=42)

In [13]:
heart_model = RandomForestClassifier(random_state=42)
heart_model.fit(x_train_heart, y_train_heart)

RandomForestClassifier(random_state=42)

In [14]:
y_pred_dia = dia_model.predict(x_test_dia)
print(f"Accuracy         : {accuracy_score(y_test_dia, y_pred_dia)*100:.2f}%","\n---------")
print(f"Confusion Matrix :\n{confusion_matrix(y_test_dia, y_pred_dia)}","\n---------")
print(f"Classification Report :\n{classification_report(y_test_dia, y_pred_dia)}")

Accuracy         : 72.08% 
---------
Confusion Matrix :
[[77 22]
 [21 34]] 
---------
Classification Report :
              precision    recall  f1-score   support

           0       0.79      0.78      0.78        99
           1       0.61      0.62      0.61        55

    accuracy                           0.72       154
   macro avg       0.70      0.70      0.70       154
weighted avg       0.72      0.72      0.72       154



In [15]:
y_pred_heart = heart_model.predict(x_test_heart)
print(f"Accuracy         : {accuracy_score(y_test_heart, y_pred_heart)*100:.2f}%","\n---------")
print(f"Confusion Matrix :\n{confusion_matrix(y_test_heart, y_pred_heart)}","\n---------")
print(f"Classification Report :\n{classification_report(y_test_heart, y_pred_heart)}")

Accuracy         : 76.19% 
---------
Confusion Matrix :
[[75 29]
 [21 85]] 
---------
Classification Report :
              precision    recall  f1-score   support

           0       0.78      0.72      0.75       104
           1       0.75      0.80      0.77       106

    accuracy                           0.76       210
   macro avg       0.76      0.76      0.76       210
weighted avg       0.76      0.76      0.76       210



In [16]:
scaler = StandardScaler()
X_train_neu_scaled = scaler.fit_transform(x_train_neu)
X_test_neu_scaled = scaler.transform(x_test_neu)

In [17]:
neu_model = SVC(random_state=42)
neu_model.fit(X_train_neu_scaled, y_train_neu)

SVC(random_state=42)

In [18]:
y_pred_neu = neu_model.predict(X_test_neu_scaled)
print(f"Accuracy         : {accuracy_score(y_test_neu, y_pred_neu)*100:.2f}%","\n---------")
print(f"Confusion Matrix :\n{confusion_matrix(y_test_neu, y_pred_neu)}","\n---------")
print(f"Classification Report :\n{classification_report(y_test_neu, y_pred_neu)}")

Accuracy         : 53.00% 
---------
Confusion Matrix :
[[43 52]
 [42 63]] 
---------
Classification Report :
              precision    recall  f1-score   support

           0       0.51      0.45      0.48        95
           1       0.55      0.60      0.57       105

    accuracy                           0.53       200
   macro avg       0.53      0.53      0.53       200
weighted avg       0.53      0.53      0.53       200



In [21]:
print("  DIABETES PREDICTION")
sample_diabetes = np.array([[6, 148, 72, 35, 0, 33.6, 0.627, 50]])

result = dia_model.predict(sample_diabetes)
print(f"Input : {sample_diabetes}")
if result[0] == 1:
    print("Output : ⚠️ Diabetes Detected!")
else:
    print("Output : ✅ No Diabetes")

  DIABETES PREDICTION
Input : [[  6.    148.     72.     35.      0.     33.6     0.627  50.   ]]
Output : ⚠️ Diabetes Detected!


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [22]:
print("  HEART DISEASE PREDICTION")
sample_heart = np.array([[52, 1, 2, 130, 250, 0, 1, 160, 0, 1.2, 2]])

result = heart_model.predict(sample_heart)
print(f"Input : {sample_heart}")
if result[0] == 1:
    print("Output : ⚠️ Heart Disease Detected!")
else:
    print("Output : ✅ No Heart Disease")

  HEART DISEASE PREDICTION
Input : [[ 52.    1.    2.  130.  250.    0.    1.  160.    0.    1.2   2. ]]
Output : ⚠️ Heart Disease Detected!


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [26]:
print("  NEUROLOGICAL PREDICTION")
sample_neu = np.array([[119.992, 157.302, 74.997, 0.00784, 0.00007,
                        0.00370, 0.00554, 0.01109, 0.04374, 0.42600,
                        0.02182, 0.03130, 0.02971, 0.06545, 0.02211,
                        0.01428, 21.640, 0.41888, 0.54842, -4.117,
                        0.33559, 2.48685]])

result = neu_model.predict(sample_neu)
print(f"Input : {sample_neu}")
if result[0] == 1:
    print("Output : ⚠️ Neurological Disorder Detected!")
else:
    print("Output : ✅ No Neurological Disorder")

  NEUROLOGICAL PREDICTION
Input : [[ 1.19992e+02  1.57302e+02  7.49970e+01  7.84000e-03  7.00000e-05
   3.70000e-03  5.54000e-03  1.10900e-02  4.37400e-02  4.26000e-01
   2.18200e-02  3.13000e-02  2.97100e-02  6.54500e-02  2.21100e-02
   1.42800e-02  2.16400e+01  4.18880e-01  5.48420e-01 -4.11700e+00
   3.35590e-01  2.48685e+00]]
Output : ✅ No Neurological Disorder
